# Generated by Django 4.1.1 on 2022-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('long_url', models.URLField()),
                ('ShortURL', models.CharField(blank=True, max_length=15, unique=True)),
                ('UsedCount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
