# Generated by Django 4.1.1 on 2022-09-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshorterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortener',
            old_name='long_url',
            new_name='LongURL',
        ),
    ]
